name: Despliegue Autom치tico en Producci칩n

on: 
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

      - name: Construir
        run: npm run build

      - name: Despliegue a entorno de producci칩n
        run: |
          echo "Comando de despliegue a producci칩n"
